services:
  redis-runtime:
    image: redis:7-alpine
    command: ["redis-server", "--port", "6381"]

  app:
    build:
      context: ..
      dockerfile: playground/Dockerfile
    environment:
      NUXT_REDIS_URL: redis://redis-runtime:6381/0
    depends_on:
      - redis-runtime

  workers:
    build:
      context: ..
      dockerfile: playground/Dockerfile
    command: ["node", ".output/server/workers/index.mjs"]
    environment:
      NUXT_REDIS_URL: redis://redis-runtime:6381/0
    depends_on:
      - redis-runtime
